spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 714731887016-0h35lmpp1hv6v81iq8k2gr70q7ebm85h.apps.googleusercontent.com
            client-secret: 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

server:
  port: 8080